// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOALaqtFJlfsyz-0tuBppYPtC8ePYRUdk',
    appId: '1:722836552072:web:058673cabc92e11e05e23d',
    messagingSenderId: '722836552072',
    projectId: 'form-a10d0',
    authDomain: 'form-a10d0.firebaseapp.com',
    storageBucket: 'form-a10d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BMdRmeNPJnJOZykD2h5rMJDgKg1z-n0',
    appId: '1:722836552072:android:79605a2a28111a0a05e23d',
    messagingSenderId: '722836552072',
    projectId: 'form-a10d0',
    storageBucket: 'form-a10d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCTvVqzY0sxd__IVF6NCBByof0sklHfq0',
    appId: '1:722836552072:ios:09624de4c01029d005e23d',
    messagingSenderId: '722836552072',
    projectId: 'form-a10d0',
    storageBucket: 'form-a10d0.appspot.com',
    iosClientId:
        '722836552072-61hjk6befbbph9gdrdiqgog6is5p27ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.feedback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCTvVqzY0sxd__IVF6NCBByof0sklHfq0',
    appId: '1:722836552072:ios:09624de4c01029d005e23d',
    messagingSenderId: '722836552072',
    projectId: 'form-a10d0',
    storageBucket: 'form-a10d0.appspot.com',
    iosClientId:
        '722836552072-61hjk6befbbph9gdrdiqgog6is5p27ju.apps.googleusercontent.com',
    iosBundleId: 'com.example.feedback',
  );
}
