// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTIVy_wtfc9cf6HufMp5d99n-fwYi_UWQ',
    appId: '1:139849338729:web:ef82a50a8df366b584f7f8',
    messagingSenderId: '139849338729',
    projectId: 'books-fe392',
    authDomain: 'books-fe392.firebaseapp.com',
    databaseURL: 'https://books-fe392-default-rtdb.firebaseio.com',
    storageBucket: 'books-fe392.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUZ9v0rzYlCdSjnCQ_R7wgz3vFaBI6pqg',
    appId: '1:139849338729:android:a3dc0d80af651ca684f7f8',
    messagingSenderId: '139849338729',
    projectId: 'books-fe392',
    databaseURL: 'https://books-fe392-default-rtdb.firebaseio.com',
    storageBucket: 'books-fe392.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMLqdYBAunWmlYqznmL0aYz03NtwL7cRo',
    appId: '1:139849338729:ios:12972916ac3bb0c384f7f8',
    messagingSenderId: '139849338729',
    projectId: 'books-fe392',
    databaseURL: 'https://books-fe392-default-rtdb.firebaseio.com',
    storageBucket: 'books-fe392.appspot.com',
    iosClientId: '139849338729-6ne85ra9jjqql1s7h8s3aug7fprg1i7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMLqdYBAunWmlYqznmL0aYz03NtwL7cRo',
    appId: '1:139849338729:ios:12972916ac3bb0c384f7f8',
    messagingSenderId: '139849338729',
    projectId: 'books-fe392',
    databaseURL: 'https://books-fe392-default-rtdb.firebaseio.com',
    storageBucket: 'books-fe392.appspot.com',
    iosClientId: '139849338729-6ne85ra9jjqql1s7h8s3aug7fprg1i7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );
}
